version: 2.1
commands: # a reusable command with parameters
  command_build_and_test:
    parameters:
      jobId:
        default: "unset"
        type: string
    steps:
      # Restore the dependency cache
      - restore_cache:
          keys:
            # Default branch if not
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      # The following `checkout` command checks out your code to your working directory. In 1.0 we did this implicitly. In 2.0 you can choose where in the course of a job your code should be checked out.
      - checkout
      # Prepare for artifact and test results  collection equivalent to how it was done on 1.0.
      # In many cases you can simplify this from what is generated here.
      # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      # This is based on your 1.0 configuration file or project settings
      - run:
          command: java -version
      # Test
      - run:
          name: "Setup custom environment variables"
          command: echo 'export CIRCLE_JOB_ID="<<parameters.jobId>>"' >> $BASH_ENV
      - run: ./.circleci/parallel.sh
      # Save dependency cache
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            # This is a broad list of cache paths to include many possible development environments
            # You can probably delete some of these entries
            - vendor/bundle
            - ~/.pyenv
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.bundle
            - ~/.gradle
            - ~/.cache/bower
            - ".git"
            - ~/.stack
      # save "default" cache using the key "source-v2-"
      - save_cache:
          key: source-v2-
          paths:
            # This is a broad list of cache paths to include many possible development environments
            # You can probably delete some of these entries
            - vendor/bundle
            - ~/.pyenv
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.bundle
            - ~/.gradle
            - ~/.cache/bower
            - ".git"
            - ~/.stack
      # Teardown
      #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
  command_docker_build_and_test:
    parameters:
      jobId:
        default: "unset"
        type: string
    steps:
      # Machine Setup
      #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
      # The following `checkout` command checks out your code to your working directory. In 1.0 we did this implicitly. In 2.0 you can choose where in the course of a job your code should be checked out.
      - checkout
      # Prepare for artifact and test results  collection equivalent to how it was done on 1.0.
      # In many cases you can simplify this from what is generated here.
      # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: "Setup custom environment variables"
          command: echo 'export CIRCLE_JOB_ID="<<parameters.jobId>>"' >> $BASH_ENV
      - run: ./.circleci/parallel.sh
      # Teardown
      #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
jobs:
  ensureSamplesAndGeneratorDocsUpToDate:
    machine:
      image: ubuntu-2004:202201-02
    working_directory: ~/OpenAPITools/openapi-json-schema-generator
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - command_build_and_test:
          jobId: "ensureSamplesAndGeneratorDocsUpToDate"
  mvnCleanInstallJava11:
    machine:
      image: ubuntu-2004:202201-02
    working_directory: ~/OpenAPITools/openapi-json-schema-generator
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - command_build_and_test:
          jobId: "mvnCleanInstall"
  mvnCleanInstallJava21:
    machine:
      image: ubuntu-2204:2023.07.2
    working_directory: ~/OpenAPITools/openapi-json-schema-generator
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - command_build_and_test:
          jobId: "mvnCleanInstall"
  testPython38ClientSamples:
    docker:
      - image: python:3.8
    working_directory: ~/OpenAPITools/openapi-json-schema-generator
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - command_docker_build_and_test:
          jobId: "testPythonClientSamples"
  testPython39ClientSamples:
    docker:
      - image: python:3.9
    working_directory: ~/OpenAPITools/openapi-json-schema-generator
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - command_docker_build_and_test:
          jobId: "testPythonClientSamples"
workflows:
  version: 2
  build:
    jobs:
      - ensureSamplesAndGeneratorDocsUpToDate
      - mvnCleanInstallJava11
      - mvnCleanInstallJava21
      - testPython38ClientSamples
      - testPython39ClientSamples
