generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/browser
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript
additionalProperties:
  framework: fetch-api
  npmName: ts-petstore-client
  projectName: ts-petstore-client
  moduleName: petstore
  supportsES6: true
